### ISSUE TITLE
add temporary directory creation/cleanup

### ISSUE THREAD

**Issue by drlight-code** [project-arcana/nexus#28]
We could have a `nx::get_temp_directory()` or the like that yields a temporary directory for intermediate disk IO during tests. Nexus could take care of cleaning up the directory for all succeded tests. This should be optional via a cmdline flag such as `--no-delete-temp` for debugging and development purposes.

**Comment by jkunstwald** [comment]
Would writing to the system temp directory work? Cleaning up would be taken care of, and the files are still available after running tests.
Im not sure about „temp folder conventions“ on Posix systems, on Win32 this is `GetTempPath`, since C++17 there is an STL equivalent:
https://en.cppreference.com/w/cpp/filesystem/temp_directory_path

**Comment by drlight-code** [comment]
tmp folders typically get created under `/tmp`, `/var/tmp` or `/var/run`. To quote the filesystem hierarchy standard manpage:
```
       /tmp   This  directory  contains temporary files which may be deleted with no notice, such as by a regular job or at system boot
              up.

       /var/run
              Run-time variable files, like files holding process identifiers (PIDs) and logged user information (utmp).  Files in this
              directory are usually cleared when the system boots.
       /var/tmp
              Like /tmp, this directory holds temporary files stored for an unspecified duration.
```
It seems the STL function returns `/tmp` by default. The idea was more to have an automatic teardown of the test fixture after tests succed. Otherwise things might start to accumulate during development when tests are run many times. And it would be a bit of a burden if every test would have to take care to clean every file it writes for testing purposes.

**Comment by jkunstwald** [comment]
I see, so this would be a good feature to have in nexus. Say we don't want to create those temporary files in the working directory, would the system temp folder be a good place permission-wise? ie `<OS temp dir>/arcana-nexus/<GUID>/`. On win32 you can always write to Temp/ i think, is it the same on linux?

**Comment by drlight-code** [comment]
Yep, the tmp folder returned by `temp_directory_path` should be world-writable. 
```
$ ls -ld /tmp/
drwxrwxrwt 14 root root 320 Nov 10 11:43 /tmp/
```
We could discuss wether a unique folder is needed per test or per run. I think unique per test would be sufficient. Then the question is how to deal with pre-existing directories (in case the last test run failed). I think it should be deleted so that the fixture is always reproducible.

**Comment by jkunstwald** [comment]
In that case we wouldn't even require a `--no-delete-temp` flag, right? Directories are named according to test name and possibly some namespacing, and are cleaned when a test is ran (or once it first requests the path). After running, the folders remain there for examination in whatever state they were left, and "global cleanup" is taken care of by the OS in some way since it's all in temp.

**Comment by drlight-code** [comment]
That would also be OK I guess, hoping that single tests won't generate terabytes of data ;)

**Comment by jkunstwald** [comment]
Is there a linux native version of temp_directory_path? Maybe we can avoid dragging in `<filesystem>` since it's pretty heavyweight

**Comment by drlight-code** [comment]
The POSIX compliant way to do it would be to use `$TMPDIR` if defined and `/tmp` otherwise.
https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap10.html

**Comment by drlight-code** [comment]
There seem to be differenr temp file/dir methods provided by the C standard library:
https://www.gnu.org/software/libc/manual/html_node/Temporary-Files.html

**Comment by jkunstwald** [comment]
> The POSIX compliant way to do it would be to use `$TMPDIR` if defined and `/tmp` otherwise.
> https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap10.html

Ok easy enough, i'd use that for an implementation.

The C std functions don't seem to do what we want here, tmpfile auto-deletes the files unconditionally, and there are concerns with thread safety and permissions apparently.
